apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: flask-app
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
      - image: flask-app
        ports:
        - name: http1
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /status